### ISSUE TITLE
Wrong with :python ../code/utils/extract_official_train_test_set_from_mat.py nyu_depth_v2_labeled.mat splits.mat ./nyu_depth_v2/official_splits/

### ISSUE THREAD

**Issue by Hikeylin** [vinvino02/GLPDepth#22]
(glp) ning@ubuntu:~/GLPDepth/datasets$ python ../code/utils/extract_official_train_test_set_from_mat.py nyu_depth_v2_labeled.mat splits.mat ./nyu_depth_v2/official_splits/
Traceback (most recent call last):
  File "../code/utils/extract_official_train_test_set_from_mat.py", line 36, in <module>
    import h5py
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 17, in init h5py._conv
  File "/home/ning/GLPDepth/code/utils/logging.py", line 7, in <module>
    import torch
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/__init__.py", line 751, in <module>
    from .functional import *  # noqa: F403
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/functional.py", line 8, in <module>
    import torch.nn.functional as F
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/nn/__init__.py", line 1, in <module>
    from .modules import *  # noqa: F403
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/nn/modules/__init__.py", line 2, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 6, in <module>
    from .. import functional as F
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/nn/functional.py", line 18, in <module>
    from .._jit_internal import boolean_dispatch, _overload, BroadcastingList1, BroadcastingList2, BroadcastingList3
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/_jit_internal.py", line 24, in <module>
    import torch.distributed.rpc
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/distributed/__init__.py", line 55, in <module>
    from .distributed_c10d import *  # noqa: F403
  File "/home/ning/miniconda3/envs/glp/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 63, in <module>
    logger = logging.getLogger(__name__)
AttributeError: module 'logging' has no attribute 'getLogger'

**Comment by vinvino02** [comment]
It seems that this error is caused by duplicate names of **logging** (from my code and from h5py library). You could rename utils/logging.py in our codes and try again.

**Comment by premchedella** [comment]
I also got this error, moved logging.py in code\utils folder to glp_depth_logging.py
